### ISSUE TITLE
Template string with component 

### ISSUE THREAD

**Issue by rbajaniya** [egoist/vue-html#1]
Hello,

I have render html with your plugin then it works fine with normal html but I have create one component for ex. Breadcrumb and render html with component but it not working. Please help me if it is possible.

=> For more help please review my code 

```
<script>
import Breadcrumb from '~components/Breadcrumb'
import Vue from 'vue'
import HTML from 'vue-html'

Vue.use(HTML)

export default {
  data () {
    return {
      html: '<div><Breadcrumb/></div>'
    }
  },
  render (h) {
    return this.$html(this.html)
  },
  components: {
    Breadcrumb
  }
}
</script>
```

**Comment by egoist** [comment]
You have to use tagged template string like <code>this.$html\`${this.html}\`</code>

**Comment by rbajaniya** [comment]
`this.$html${this.html}` put inside render function?

**Comment by egoist** [comment]
Yeah, that's what you should return in render function, basically it creates vnode from given string.

**Comment by rbajaniya** [comment]
It's gives error

```
Syntax Error: Unexpected token, expected ; (24:22)

  22 |   },
  23 |   render (h) {
> 24 |     return this.$html${this.html}
     |                       ^
  25 |   },
  26 |   components: {
  27 |     Breadcrumb
```

**Comment by egoist** [comment]
You forgot backticks

**Comment by rbajaniya** [comment]
Ohhh sorry,

I have put with backticks then resolved error but in browser not render template.

**Comment by egoist** [comment]
Check out the new usages: https://github.com/egoist/vue-html#usage
