### ISSUE TITLE
Render string with space separated attribute content

### ISSUE THREAD

**Issue by andresviviani1** [egoist/vue-html#2]
Hello, I'm trying to test your library with a very basic code: 
`const test = '<p class="a b">Just a test</p>'`

However I get an error and the rendered HTML is:

`<p a="a" b"="b"" class="class">Just a test</p>` 

Am I doing something wrong?

This is the error I'm getting: 

> [nuxt] Error while initializing app DOMException: Failed to execute 'setAttribute' on 'Element': 'b"' is not a valid attribute name.

I would like to add a component, however, for now, it is just a test. The complete test should be: 
`const test = '<p class="a b">Just a test <my-component component-data="data"> </my-component> </p>'`

**Comment by egoist** [comment]
Try v1.
